version: '3'

services:
  redu-ms2-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: redu.ucsd.edu
      #VIRTUAL_HOST: mingwangbeta.ucsd.edu
      VIRTUAL_PORT: 5005
      LETSENCRYPT_HOST: redu.ucsd.edu
      #LETSENCRYPT_HOST: mingwangbeta.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu

networks:
  nginx-net:
    external:
      name: nginx-net