version: '3'

services:
  redu-ms2-web:
    build: .
    ports:
      - "5005:5001"
    volumes:
      - ../database/:/app/database
      - ../temp/:/app/temp
      - ../logs/:/app/logs
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: redu.ucsd.edu
      VIRTUAL_PORT: 5005
      LETSENCRYPT_HOST: redu.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu
    deploy:
      resources:
        limits:
          memory: 8000M  

  redu-ms2-populate:
    build: .
    volumes:
      - ../database/:/app/database
      - ../temp/:/app/temp
    command: /app/utilities/continuous_metadata_update.sh
    deploy:
      resources:
        limits:
          memory: 8000M

networks:
  nginx-net:
    external:
      name: nginx-net