version: '3'

services:
  redu-ms2-web:
    build: .
    ports:
      - "5005:5001"
    volumes:
      - ../database/:/app/database
      - ../temp/:/app/temp
      - ../logs/:/app/logs
    command: /app/run_server.sh

  redu-ms2-populate:
    build: .
    volumes:
      - ../database/:/app/database
      - ../temp/:/app/temp
    command: /app/utilities/continuous_metadata_update.sh
